name: ✨ Feature Request
description: Suggest a new feature or enhancement for prenivdlapp-cli
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees:
  - arsya371

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature would be useful for other users, not just me
          required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New platform support
        - Enhancement to existing platform
        - CLI improvement
        - Performance improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    id: platform-details
    attributes:
      label: Platform Details (if requesting new platform)
      description: If requesting support for a new platform, provide details
      placeholder: |
        - Platform name:
        - Website URL:
        - Content types (video/audio/image):
        - Any known APIs or tools:
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Critical for my use case
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would like to work on this feature myself
          required: false
